### PR TITLE
Update sbt, akka, webjars-locator-core, sbt-web-build-base

### PR DESCRIPTION
**Pull request by mkurz**

### CODE REVIEW

**Comment by benmccann** [comment]
Travis failed

**Comment by mkurz** [comment]
@benmccann Its green now. I also want to upgrade `sbt-web-build-base` after https://github.com/sbt/sbt-web-build-base/pull/6 got merged and a new release got cut. Afterwards we could cut a new `sbt-web` release as well.
(However this pull request can be merged already.

**Comment by mkurz** [comment]
BTW: I switched to adoptopenjdk.

**Comment by mkurz** [comment]
`sbt-web-build-base` 1.2.2 was cut already and included in this pr. Can someone cut a new `sbt-web` release? Thanks!

**Pull request merged**
