### PR TITLE
Upgrade dependencies and publish to bintray

### PR DESCRIPTION
**Pull request by jroper**
* Upgraded all dependencies
* Published to bintray

### CODE REVIEW

**Comment by retronym** [comment]
I believe that this patch caused a failure in the community build.

https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x/518/consoleText

```
[sbt-web] Publishing: default-sbt-project
[sbt-web] bintray-sbt requires your bintray credentials.
[sbt-web] [warn] Credentials file /home/jenkinsdbuild2/.bintray/.credentials does not exist
[sbt-web] Enter bintray username: java.util.NoSuchElementException: None.get
[sbt-web] 	at scala.None$.get(Option.scala:313)
[sbt-web] 	at scala.None$.get(Option.scala:311)
[sbt-web] 	at bintray.Prompt$.apply(prompt.scala:12)
[sbt-web] 	at bintray.Plugin$.bintray$Plugin$$requestCredentials(plugin.scala:179)
[sbt-web] 	at bintray.Plugin$$anonfun$bintray$Plugin$$ensuredCredentials$2.apply(plugin.scala:200)
[sbt-web] 	at bintray.Plugin$$anonfun$bintray$Plugin$$ensuredCredentials$2.apply(plugin.scala:196)
[sbt-web] 	at scala.util.Either.fold(Either.scala:98)
[sbt-web] 	at bintray.Plugin$.bintray$Plugin$$ensuredCredentials(plugin.scala:196)
[sbt-web] 	at bintray.Plugin$$anonfun$ensureCredentialsTask$1.apply(plugin.scala:163)
[sbt-web] 	at bintray.Plugin$$anonfun$ensureCredentialsTask$1.apply(plugin.scala:163)
[sbt-web] 	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
[sbt-web] 	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
[sbt-web] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[sbt-web] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[sbt-web] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[sbt-web] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[sbt-web] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[sbt-web] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[sbt-web] 	at sbt.Execute.work(Execute.scala:235)
```

@cunei @jsuereth Is there a way to switch to bintray publishing that plays nicely with dbuild?

/cc @lrytz / @adriaanm

**Comment by jroper** [comment]
This will also need to be addressed for RP.

**Comment by jsuereth** [comment]
I think this is a misbehavior in the bintray plugin.  We'll look for a workaround

**Comment by retronym** [comment]
Thanks, @jsuereth.

More generally than dbuild, it is really important that the publishing mechanisms of a project never get of someone building it for some other reason (this issue reminds me of the usability problems in earlier versions of sbt-pgp.)

**Comment by jroper** [comment]
I don't think it's a misbehaviour of the bintray plugin - it's a feature.  The bintray plugin overrides the publish method, because it needs to do some extra work publishing details to bintray about the release using the bintray rest API.  I'm not exactly sure what, or if it's necessary.  But in order to support publishing to different places, we'll need to have a way to disable the bintray plugin.

**Comment by huntc** [comment]
Perhaps a solution is to migrate the bintray plugin to an auto plugin and then use `disablePlugins` on the project if/when required.

**Comment by jroper** [comment]
That would work for people who manually publish to other locations (and could be more effort than that, since it would require disabling it on every module that used it, and also, if the module modified a task/setting, that configuration would have to be removed because without the plugin, it can't depend on the old value), but it wouldn't work for automatic tools like dbuild that (rightly) have no knowledge of bintray.

**Comment by eed3si9n** [comment]
I turned bintray-sbt into an auto plugin, and also separated the releasing from `publish` (staging).
The PR softprops/bintray-sbt#53 was sent last night, but while we wait for it I've also published a personal snapshot on bintray under a different organization for testing.
On my machine I was able to run `publish` without `.credential` file.

See #107.

**Pull request merged**
